# protocol control messages
TYPE_CONTROL_SET_CHUNK = 1
TYPE_CONTROL_ABORT_MESSAGE = 2
TYPE_CONTROL_ACK = 3
TYPE_CONTROL_ACK_SIZE = 5
TYPE_CONTROL_SET_BANDWIDTH = 6
RTMP_CONTROL_TYPES = [TYPE_CONTROL_SET_CHUNK, TYPE_CONTROL_ABORT_MESSAGE,
                      TYPE_CONTROL_ACK, TYPE_CONTROL_ACK_SIZE, TYPE_CONTROL_SET_BANDWIDTH]

# streaming control message
TYPE_USER_CONTROL_MESSAGE = 4
USER_CONTROL_StreamBegin = 0x00
USER_CONTROL_StreamEOF = 0x01
USER_CONTROL_StreamDry = 0x02
USER_CONTROL_SetBufferLength = 0x03
USER_CONTROL_StreamIsRecorded = 0x04
USER_CONTROL_PingRequest = 0x05
USER_CONTROL_PingResponse = 0x06

# amf0 encoded message
TYPE_AMF0_COMMAND = 20
TYPE_AMF0_DATA = 18
TYPE_AMF0_SO = 19
AMFO_TYPES = [TYPE_AMF0_SO, TYPE_AMF0_COMMAND, TYPE_AMF0_DATA]

# amf3 encoded message
TYPE_AMF3_COMMAND = 17
TYPE_AMF3_DATA = 15
TYPE_AMF3_SO = 16
AMF3_TYPES = [TYPE_AMF3_SO, TYPE_AMF3_COMMAND, TYPE_AMF3_DATA]

# misc types
TYPE_VIDEO = 9
TYPE_AUDIO = 8
TYPE_AGGREGATE = 22

# rtmp command messages
COMMANDS_NetConnection = ['connect', 'call', 'close', 'createStream']

# rtmp audio flag
SUPPORT_SND_NONE = 0x0001
SUPPORT_SND_MP3 = 0x0004
SUPPORT_SND_AAC = 0x0400
SUPPORT_SND_ALL = 0x0FFF

# rtmp video flag
SUPPORT_VID_H264 = 0x0080
SUPPORT_VID_ALL = 0x00FF
SUPPORT_VID_CLIENT_SEEK = 0x01